version: '3.8'

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/conf:/etc/mysql/conf.d
    networks:
      - inception-network

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - certs:/etc/ssl/certs
      - wordpress_data:/var/www/html:ro
    networks:
      - inception-network

volumes:
  mariadb_data:
  wordpress_data:
  certs:

networks:
  inception-network:
    driver: bridge